name: 'Set up and build Flutter App'

inputs:
  map-api-key-id:
    required: true
    description: "Naver map API Client ID"
  api-host:
    required: true
    description:  ""
  platform:
    required: true
    description: "Target platform for build: web, appbundle, apk, ios, etc."
  build-mode:
    required: false
    default: release
    description: "Build mode: release(default), profile, or debug"
  build-options:
    required: false
    description: "Additional run options"

runs:
  using: "composite"

  steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.29.2"

    - name: Install dependencies
      shell: bash
      run: flutter pub get

    - name: Generate GraphQL Schema & Models
      shell: bash
      run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: Build Flutter
      shell: bash
      run: |
        flutter build \
          ${{inputs.platform}} \
          --${{inputs.build-mode}} \
          --dart-define=NAVER_MAP_CLIENT_ID=${{ inputs.map-api-key-id }} \
          --dart-define=API_URL=https://${{ inputs.api-host }}/api/graphql \
          ${{inputs.build-options}}