name: 'Build image with Docker buildx'

inputs:  
  tag:
    required: true
  image-name:
    description: "Image name in the format: org/image or owner/image."
    required: true
    
  dockerfile:
    description: "Path to the Dockerfile"
    required: false
    default: "./Dockerfile"

runs:
  using: "composite"
  steps:
  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3

  - name: Login to GitHub Container Registry
    uses: docker/login-action@v3
    with:
      registry: ghcr.io
      username: ddd-cute-bot
      password: ${{ secrets.GHCR_TOKEN }}

  - name: Build and push Docker image
    uses: docker/build-push-action@v6
    with:
      context: .
      file: ${{ inputs.dockerfile }}
      platforms: linux/amd64,linux/arm64
      push: true
      tags: ghcr.io/${{ inputs.image-name }}:${{ inputs.tag }}
