name: 'Build Flutter Web'
runs:
  using: "composite"
  steps:
  - name: Setup Flutter
    uses: subosito/flutter-action@v2
    with:
      flutter-version: 'stable'

  - name: Install Dependencies
    run: flutter pub get

  - name: Build Flutter Web
    run: flutter build web --release
