name: 'Set up and build Flutter web'

inputs:
  NAVER_MAP_CLIENT_ID:
    required: true
    description: "Naver map API Client ID"
  HOST:
    required: true
    description:  ""

runs:
  using: "composite"

  steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.29.2"

    - name: Install dependencies
      run: flutter pub get
      shell: bash

    - name: Generate GraphQL Schema & Models
      run: flutter pub run build_runner build --delete-conflicting-outputs
      shell: bash

    - name: Build Flutter Web
      run: |
        flutter build web --release \
          --dart-define=NAVER_MAP_CLIENT_ID=${{ inputs.NAVER_MAP_CLIENT_ID }} \
          --dart-define=API_URL=https://${{ inputs.HOST }}/api/graphql --base-href /
      shell: bash
