name: 'Build and Push Image with Docker Buildx'

inputs:  
  dockerfile:
    description: "Path to the Dockerfile"
    required: false
    default: "./Dockerfile"
  tags:
    description: "List of tags, seperated by comma"
    required: true
  registry:
    description: "Docker registry"
    required: false
    default: "ghcr.io"
  username:
    description: "Docker username"
    required: false
    default: "ddd-cute-bot"
  password:
    description: "Docker password"
    required: true

runs:
  using: "composite"
  steps:
  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3

  - name: Login to Registry
    uses: docker/login-action@v3
    with:
      registry: ${{ inputs.registry }}
      username: ${{ inputs.username }}
      password: ${{ inputs.password }}

  - name: Build and Push Docker image
    uses: docker/build-push-action@v6
    with:
      context: .
      file: ${{ inputs.dockerfile }}
      platforms: linux/amd64,linux/arm64
      push: true
      tags: ${{ inputs.tags }}
